# To run: conda env create -f environment.yml
name: prune_nerf
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - cudatoolkit=10.0
    - tensorflow-gpu==1.15
    - numpy
    - matplotlib
    - imageio
    - imageio-ffmpeg
    - configargparse
    - imagemagick
    - keras
    - pip:
        - git+https://www.github.com/keras-team/keras-contrib.git
